[package]
name = "hpke"
version = "0.0.2-dev"
authors = ["Franziskus Kiefer <franziskuskiefer@gmail.com>"]
edition = "2018"
license = "MPL-2.0"
documentation = "https://docs.rs/hpke-rs"
description = "HPKE Implementation using Evercrypt"
readme = "README.md"

[dependencies]
evercrypt = { version = "0.0.1" }

[patch.crates-io]
evercrypt = { git = "https://github.com/franziskuskiefer/evercrypt-rust" }

[dev-dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
