[package]
name = "hpke"
version = "0.0.2-dev2"
authors = ["Franziskus Kiefer <franziskuskiefer@gmail.com>"]
edition = "2018"
license = "MPL-2.0"
documentation = "https://docs.rs/hpke-rs"
description = "HPKE Implementation using Evercrypt"
readme = "README.md"

[dependencies]
evercrypt = { version = "0.0.3-dev3" }

[patch.crates-io]
evercrypt = { git = "https://github.com/franziskuskiefer/evercrypt-rust", package = "evercrypt" }
evercrypt-sys = { git = "https://github.com/franziskuskiefer/evercrypt-rust", package = "evercrypt-sys" }

[features]
rust-crypto = ["evercrypt/rust-crypto-aes"]

[dev-dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
