[package]
name = "hpke"
version = "0.1.0"
authors = ["Franziskus Kiefer <franziskuskiefer@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Evercrypt
evercrypt = { git = "https://github.com/franziskuskiefer/evercrypt-rust", branch = "master" }
# evercrypt = { path = "../evercrypt-rust/evercrypt-rs" }

[dev-dependencies]
serde_json = "1.0"
serde = {version = "1.0", features = ["derive"]}
