[package]
name = "hpke-rs"
version = "0.0.5"
authors = ["Franziskus Kiefer <franziskuskiefer@gmail.com>"]
edition = "2018"
license = "MPL-2.0"
documentation = "https://www.franziskuskiefer.de/hpke-rs"
description = "HPKE Implementation using Evercrypt"
readme = "README.md"
repository = "https://github.com/franziskuskiefer/hpke-rs"

[dependencies]
evercrypt = { version = "0.0.7", git = "https://github.com/franziskuskiefer/evercrypt-rust" }
serde_json = { version = "1.0", optional = true }
serde = { version = "1.0", features = ["derive"], optional = true }

[features]
rust-crypto = ["evercrypt/rust-crypto-aes"]
serialization = ["serde", "serde_json", "evercrypt/serialization"]
hazmat = []

[dev-dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
lazy_static = "1.4"
